spring.application.name=homepage

## jsp 요청 시 한글 prefix와 suffix를 제대로 처리하는 방법
## view resolver 설정
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

## jdbc 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=webuser
spring.datasource.password=123456

## Mybatis 설정
mybatis.config-location=classpath:mybatis-config.xml
##DAO 객체를 자동으로 맵핑하여, 자동 DAO 객체의 이름을 설정함
##매핑 시스템 xml을 설정합니다
mybatis.mapper-locations=classpath:mappers/**/*.xml

##콘솔 메시지
spring.messages.basename=message

##업로드 파일, 최대 크기 제한 (기본: 1MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

##파일 업로드 경로 (기본 경로는 파일시스템에서 설정한 jsp 페이지의 특정 경로로)
upload.path=c:/upload/